import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import axios from "axios";
import { Food } from "../interfaces/Food";

export async function getStaticProps() {
  const foodsData = (await axios.get("http://127.0.0.1:1337/api/foods/")).data.data;

  return {
    props: {
      foods: foodsData,
    },
  };
}

const Home: NextPage = ({ foods }: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          {foods.map((food:Food) => (
            <a href='https://nextjs.org/docs' className={styles.card} key={food.id}>
              <h2>{ food.attributes.foodName }</h2>
              <p>{ food.attributes.description }</p>
              <p>{ food.attributes.price }円</p>
            </a>
          ))}
        </div>
      </main>
    </div>
  );
};

export default Home;
